import type { Metadata } from "next";
import "./globals.css";
import { AppWrapper } from "@/context";

export const metadata: Metadata = {
  title: "Glitters || Shop for free",
  description: "Generated by ZrCodes",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppWrapper>
          {children}
        </AppWrapper>
      </body>
    </html>
  );
}
