import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import { Mada } from "next/font/google";
import "./globals.css";

// const mada = Mada({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Glitters || Shop for free",
  description: "Generated by ZrCodes",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={mada.className}>{children}</body> */}
      <body>{children}</body>
    </html>
  );
}
